//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysOdonto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
        public string Numero { get; set; }
        public string Bairro { get; set; }
        public string Cep { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public string Telefone { get; set; }
    }
}
